# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  #contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[pt]
  languageCode = "pt"
  contentDir = "content/pt"
  title = "Escore de mortalidade ABC$_2$-SPH"
  [pt.params]
    description = "Descrição do site"
  
    
    [[pt.menu.main]]
      name = "Informações"
      url = "#hero"
      weight = 10

    [[pt.menu.main]]
      name = "Calculadora"
      url = "#calculator"
      weight = 1

    [[pt.menu.main]]
      name = "Equipe"
      url = "#team"
      weight = 55

    [[pt.menu.main]]
      name = "Publicações"
      url = "#publications"
      weight = 50
      
    [[pt.menu.main]]
      name = "Referências"
      url = "#references"
      weight = 51

    [[pt.menu.main]]
      name = "Contato"
      url = "#contact"
      weight = 70
      
    [[pt.menu.main]]
      name = "App"
      url = "#downloadapp"
      weight = 80

[es]
  languageCode = "es"
  contentDir = "content/es"
  title = "Escala de mortalidad ABC$_2$-SPH"
  [es.params]
    description = ""
  
    
    [[es.menu.main]]
      name = "Información"
      url = "#hero"
      weight = 10

    [[es.menu.main]]
      name = "Calculadora"
      url = "#calculator"
      weight = 1

    [[es.menu.main]]
      name = "Equipo"
      url = "#team"
      weight = 55

    [[es.menu.main]]
      name = "Publicación"
      url = "#publications"
      weight = 50
      
    [[es.menu.main]]
      name = "Referencias"
      url = "#references"
      weight = 51

    [[es.menu.main]]
      name = "Contacto"
      url = "#contact"
      weight = 70
      
    [[es.menu.main]]
      name = "App"
      url = "#downloadapp"
      weight = 80
